language: generic
os: linux
arch:
  - amd64
branches:
  - main
env:
  global:
  - AWS_DEFAULT_REGION=us-east-1

jobs:
  include:
    - stage: Create bootstrap resources
      env:
        - secure: "NTDkW1owt0tIXbd2BoLjcUHunQYlsD+NMW3zVASAw40KI2EavoI4ZhGg9UOe+0Aym/LaWMA7E0HNfMBNiLHochBEoxcL8rWRvCLeS1O0nNuTSx/wG/2L5AMoTkZhQ3ibfovJAN/mgkrtRk8hC/xHi5H/GxZzwEQlCT7vK2MH/xNJfStwLvcHnyYZlPcAML9b1xogETsoJyPPc9Sw1nVnJrUuT1plk3Jw/CTTYyD4JFt6tuNXBrkKpI4viAO7Kf2rdD6JQAUKw4IgRDzcoLQFIF0SSn3xQ/PQZrHF/u0e3gU+FBK/7L9vEa0IukopLJvqng12JGZtmUos1OUuKXnRcEyllshWmYz3SPPfXcV17HW741R8EMdaJ9l8ld+kWvvNArC9WGg054gTAkxf1Qz+P+9IKCE/fAjhz7AZa408dkmmnfQwr71WmmAaKHslWqru5AUOfcPa3tt+uQc7Jqn3A44m1AKvqs3yEkcGmfYy25gtKGnridCJ9sfF84sw7c4me8Nxbx+IUUtA+93txJZhWfLuxHt2Q0VUAW6T0q1MXPcaMefvz9TtmuPk5sT63brXAUlOiggjlUxyGMZtAOqAhfZYvXd713MKjkRK4iqz1Y+gMeJNN3p/TKLUwWyh/mfZVZz0yLoFOXB5aCpBM+x4+qvVKjQIGlfJHVj6mtkJoJc="
        - secure: "IYw7MGxZ06gDDxzk+LeVPUWms2XFEttQf67Wbph7VtmGJWMUzmTZxOyfncrUA1W6fJHAD1DTj4UQkSjcwGeVASCXCpGF4WaElozXS+dW1JcKpMVvDfasDiwoK+MCsPbqF0HuHhbhWqyS3/v+Pst/Qi9xOIgAcDRe6NWv8FYOEuqfvPcszWD43U2f9b7yCruUcz2DOG460u7t/PQd81jtHNeC3c/+UsPtZ1wDwS1zGJCTs2PJ3oYGH1b3lGqHoEojTIqJMLqgfCs5wv1LfAFop+zMfDwWx01bRRcF2lSopHBFkx/eart93GIeIG7ZvDAuglc7dfGoGiF7vHoabfZsVBvjCdTdNZljABUSHvAKZUvbcaTkQUJe2nI+gpXjFyCU2NafdmJWVbjGDVL9kQmr6XOexEPtGyI740MDPHiwsicKNg3zDAZb0xA3hCnL82wJiCvRWxGQHpUF3FLFJ6GwcJPAkLrwt+KWfMrVeUow2Lgi21WDmv8suNiNHZ9S7IdbMzgFa7k4+Fok4G5tM6Pfcuf9eBIDwO3DLmXTn7rPBEMtJk77SvJRhlV9WgLiU7NSgalUhu4TM5pF73kiTpUyEYb2wmIlejiP9Jwqe2guSRNEvfpq+01Xxhtxaot50RQ82v27cMKLmt03p2MwCQyryHJskl+LO6d0+3PpRbibOac="
      install:
        - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        - unzip awscliv2.zip
        - sudo ./aws/install
        - aws --version
      script:
        - cat cloudformation/bootstrap_resources.yml
        - aws cloudformation validate-template --template-body file://cloudformation/bootstrap_resources.yml
        - aws cloudformation deploy --template-file cloudformation/bootstrap_resources.yml --stack-name BootstrapResources --capabilities CAPABILITY_IAM
        - aws cloudformation list-exports | jq -r '.Exports[] | select(.Name=="BootstrapResources-RoleArn") | .Value' > rolearn
        - aws cloudformation list-exports | jq -r '.Exports[] | select(.Name=="BootstrapResources-CloudFormationTemplatesBucketName") | .Value' > cfbucketname
        - date -u +"%Y/%m/%d/%H/%M/%S" > cfkeyprefix
        - cat cfkeyprefix
      workspaces:
        create:
          name: ws1
          paths:
            - rolearn
            - cfbucketname
            - cfkeyprefix
    - stage: Validate CloudFormation templates and upload them to S3
      workspaces:
        use: ws1
      env:
        - secure: "jWw7/lFS6q0o1cpmskB/6xsFTXw8/5hGyNB0+iyZxpuuI7TA3EoEC5dtEx9R21Zp6AEROZ9bBc4VTKdEj9nyYgsKajy0Ek1MxiBRHzrqc41myP9JB/N/R//ucyBl6s/T1V9U/WjB1cplGyce3MTnk8ARAhm2sgL/e9CaTTaILZhC8ZCmr4o7vmREDU21busn7VZTqya7DdyqfR0ruLCVNjyB8T8hcIBn3ZWa2BTOFeC0jWc8EkWnOBu8dNTK1nFWzhB1nwaADfQblCZA2YS/SQ/Dfje95qUEQ9Fe638grULKFp8knFtPGrxevheyrdfXU5aUQ69aHnV3qcmDfh+nzZ2X1kK/aklEiPUT2V5zaARsQu6nN14EEncdt9AfFGhBhJgYSqjVk8lra7XE9fOwo1jI9qElyTcc0V3/duCN5zNVXt1Qs2+f6Rnhvf9wxqOGyYGdZIJ4oSfo856GYmYR0OSssScyYeybwKq7V4zHnP5z7Ycl31WJKHGBESgsryCTLWsGL0it6O9QWRr1ibS6gSrEg0UlLuT/ObKY3VZNB7eFKWtVWaPE74pX2rkRPSFb/hGMWRHO5lU6rjctt9p3m0+aNx8VN6zaA81y3e+8KliAF4Ue4VJUkmLHqkV4UWrUNQ65iSsKIh4JNIyGj3SofsaAgjmuVMq7dMHKs1AZ3wo="
        - secure: "VImb+d1EYJckHiZgg0PN8fnwAOI7PovGKDJQZDsGSu/FZdQh9niAHi4RfpxwRvuyvaNov1FWCeAyC3DDG/U5kZ6Jb3AEWD9dvhcBtBk84Bg3T4usCKcFZVbz4HPYA5G9sBZm/+xo2jRfgvCgj+onv2/cUREqFgyR20aVN2UVtiqffrETYz74qOKWv91+MLuqUDGqfpgOWksLfOjmyHR0EKBCTEXFv8cC+5DoDN77OGp9EU9weZi31on09CRTSJNBtCOfdijTF3PDN9Qn54rqa8eUQrCtnqlIz1geUElMc2EEvmByNd/lNT2RhSGanQiZpiSQ/nqHkG5LvQCsJEvnOfDZR7ie9yvYPWy/AwiR30sCvlVLl1era+oxCNRdIo0YrmUg6vrgy9Oe1K68mmb92Y0f8CIlvlarsVLtGs3SwZLcoNVYy5j86ZWSswUg0UWI8UFtuurX07fjhZVK00O2nrH8oz4xkuF6UpSHXsQZTa13m2WOEmq/U/sLJAnnLYEylDPXhz+SyEeGGtgmOzWh4uCfAJcZgEfWeX/BsC4e/xGSYJ/nr+6+vPp6qpBf53YSh9cAcBNJkomtgLAtpY89YyqWDTBpseCEmb4KVIsWYLYfu+CSAbpBu5riCVkj5QaZAd8+CWW52X5iGs4ChIHBD79QL+Awe7qkGmBe+bC/Acw="
      install:
        - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        - unzip awscliv2.zip
        - sudo ./aws/install
        - aws --version
      script:
        - export AWS_ROLE_ARN=$(cat rolearn)
        - export STS_CREDENTIALS=$(aws sts assume-role --role-arn $AWS_ROLE_ARN --role-session-name ValidateAndS3UploadTemplatesSession | jq -r '.Credentials') >/dev/null 2>&1
        - export AWS_ACCESS_KEY_ID_STS=$(echo $STS_CREDENTIALS | jq -r '.AccessKeyId') >/dev/null 2>&1
        - export AWS_SECRET_ACCESS_KEY_STS=$(echo $STS_CREDENTIALS | jq -r '.SecretAccessKey') >/dev/null 2>&1
        - export AWS_SESSION_TOKEN_STS=$(echo $STS_CREDENTIALS | jq -r '.SessionToken') >/dev/null 2>&1
        - export AWS_ACCESS_KEY_ID=$(echo $AWS_ACCESS_KEY_ID_STS) >/dev/null 2>&1
        - export AWS_SECRET_ACCESS_KEY=$(echo $AWS_SECRET_ACCESS_KEY_STS) >/dev/null 2>&1
        - export AWS_SESSION_TOKEN=$(echo $AWS_SESSION_TOKEN_STS) >/dev/null 2>&1
        - export CF_BUCKET=s3://$(cat cfbucketname)
        - export CF_KEY_PREFIX=$(cat cfkeyprefix)
        - cat cloudformation/cloudformation_template.yml
        - aws cloudformation validate-template --template-body file://cloudformation/cloudformation_template.yml
        - cat cloudformation/vpc.yml
        - aws cloudformation validate-template --template-body file://cloudformation/vpc.yml
        - aws s3 cp cloudformation/vpc.yml $CF_BUCKET/$CF_KEY_PREFIX/
        - cat cloudformation/kubernetes_infrastructure.yml
        - aws cloudformation validate-template --template-body file://cloudformation/kubernetes_infrastructure.yml
        - aws s3 cp cloudformation/kubernetes_infrastructure.yml $CF_BUCKET/$CF_KEY_PREFIX/
    - stage: Deploy CloudFormation infrastructure
      workspaces:
        use: ws1
      env:
        - secure: "jWw7/lFS6q0o1cpmskB/6xsFTXw8/5hGyNB0+iyZxpuuI7TA3EoEC5dtEx9R21Zp6AEROZ9bBc4VTKdEj9nyYgsKajy0Ek1MxiBRHzrqc41myP9JB/N/R//ucyBl6s/T1V9U/WjB1cplGyce3MTnk8ARAhm2sgL/e9CaTTaILZhC8ZCmr4o7vmREDU21busn7VZTqya7DdyqfR0ruLCVNjyB8T8hcIBn3ZWa2BTOFeC0jWc8EkWnOBu8dNTK1nFWzhB1nwaADfQblCZA2YS/SQ/Dfje95qUEQ9Fe638grULKFp8knFtPGrxevheyrdfXU5aUQ69aHnV3qcmDfh+nzZ2X1kK/aklEiPUT2V5zaARsQu6nN14EEncdt9AfFGhBhJgYSqjVk8lra7XE9fOwo1jI9qElyTcc0V3/duCN5zNVXt1Qs2+f6Rnhvf9wxqOGyYGdZIJ4oSfo856GYmYR0OSssScyYeybwKq7V4zHnP5z7Ycl31WJKHGBESgsryCTLWsGL0it6O9QWRr1ibS6gSrEg0UlLuT/ObKY3VZNB7eFKWtVWaPE74pX2rkRPSFb/hGMWRHO5lU6rjctt9p3m0+aNx8VN6zaA81y3e+8KliAF4Ue4VJUkmLHqkV4UWrUNQ65iSsKIh4JNIyGj3SofsaAgjmuVMq7dMHKs1AZ3wo="
        - secure: "VImb+d1EYJckHiZgg0PN8fnwAOI7PovGKDJQZDsGSu/FZdQh9niAHi4RfpxwRvuyvaNov1FWCeAyC3DDG/U5kZ6Jb3AEWD9dvhcBtBk84Bg3T4usCKcFZVbz4HPYA5G9sBZm/+xo2jRfgvCgj+onv2/cUREqFgyR20aVN2UVtiqffrETYz74qOKWv91+MLuqUDGqfpgOWksLfOjmyHR0EKBCTEXFv8cC+5DoDN77OGp9EU9weZi31on09CRTSJNBtCOfdijTF3PDN9Qn54rqa8eUQrCtnqlIz1geUElMc2EEvmByNd/lNT2RhSGanQiZpiSQ/nqHkG5LvQCsJEvnOfDZR7ie9yvYPWy/AwiR30sCvlVLl1era+oxCNRdIo0YrmUg6vrgy9Oe1K68mmb92Y0f8CIlvlarsVLtGs3SwZLcoNVYy5j86ZWSswUg0UWI8UFtuurX07fjhZVK00O2nrH8oz4xkuF6UpSHXsQZTa13m2WOEmq/U/sLJAnnLYEylDPXhz+SyEeGGtgmOzWh4uCfAJcZgEfWeX/BsC4e/xGSYJ/nr+6+vPp6qpBf53YSh9cAcBNJkomtgLAtpY89YyqWDTBpseCEmb4KVIsWYLYfu+CSAbpBu5riCVkj5QaZAd8+CWW52X5iGs4ChIHBD79QL+Awe7qkGmBe+bC/Acw="
      install:
        - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        - unzip awscliv2.zip
        - sudo ./aws/install
        - aws --version
      script:
        - export AWS_ROLE_ARN=$(cat rolearn)
        - export STS_CREDENTIALS=$(aws sts assume-role --role-arn $AWS_ROLE_ARN --role-session-name KubernetesStackSession  | jq -r '.Credentials') >/dev/null 2>&1
        - export AWS_ACCESS_KEY_ID_STS=$(echo $STS_CREDENTIALS | jq -r '.AccessKeyId') >/dev/null 2>&1
        - export AWS_SECRET_ACCESS_KEY_STS=$(echo $STS_CREDENTIALS | jq -r '.SecretAccessKey') >/dev/null 2>&1
        - export AWS_SESSION_TOKEN_STS=$(echo $STS_CREDENTIALS | jq -r '.SessionToken') >/dev/null 2>&1
        - export AWS_ACCESS_KEY_ID=$(echo $AWS_ACCESS_KEY_ID_STS) >/dev/null 2>&1
        - export AWS_SECRET_ACCESS_KEY=$(echo $AWS_SECRET_ACCESS_KEY_STS) >/dev/null 2>&1
        - export AWS_SESSION_TOKEN=$(echo $AWS_SESSION_TOKEN_STS) >/dev/null 2>&1
        - export CF_URL=https://$(cat cfbucketname).s3.amazonaws.com
        - export CF_KEY_PREFIX=$(cat cfkeyprefix)
        - travis_wait 30 aws cloudformation deploy --template-file cloudformation/cloudformation_template.yml --stack-name KubernetesStack --capabilities CAPABILITY_IAM --parameter-overrides CloudFormationTemplatesBucketName=$CF_URL VPCInfrastructureKey=$CF_KEY_PREFIX/vpc.yml KubernetesInfrastructureKey=$CF_KEY_PREFIX/kubernetes_infrastructure.yml