language: generic
env:
  global:
  - AWS_DEFAULT_REGION=us-east-1

jobs:
  include:
    - stage: Deploy CloudFormation role
      script: skip
      deploy:
        - provider: cloudformation
          template: cloudformation/cloudformation.yml
          stack_name: CloudFormationDeployerRole
          capabilities: CAPABILITY_IAM
          edge: true
          on:
            branch: main
    - stage: Deploy Kubernetes IAM infrastructure
      script: skip
      deploy:
        - provider: cloudformation
          template: cloudformation/iam.yml
          stack_name: KubernetesIAMInfrastructure
          capabilities: CAPABILITY_IAM
          edge: true
          on:
            branch: main
