language: generic
os: linux
arch:
  - amd64
branches:
  - main
env:
  global:
  - AWS_DEFAULT_REGION=us-east-1

jobs:
  include:
    - stage: Deploy CloudFormation role
      env:
        - secure: "NTDkW1owt0tIXbd2BoLjcUHunQYlsD+NMW3zVASAw40KI2EavoI4ZhGg9UOe+0Aym/LaWMA7E0HNfMBNiLHochBEoxcL8rWRvCLeS1O0nNuTSx/wG/2L5AMoTkZhQ3ibfovJAN/mgkrtRk8hC/xHi5H/GxZzwEQlCT7vK2MH/xNJfStwLvcHnyYZlPcAML9b1xogETsoJyPPc9Sw1nVnJrUuT1plk3Jw/CTTYyD4JFt6tuNXBrkKpI4viAO7Kf2rdD6JQAUKw4IgRDzcoLQFIF0SSn3xQ/PQZrHF/u0e3gU+FBK/7L9vEa0IukopLJvqng12JGZtmUos1OUuKXnRcEyllshWmYz3SPPfXcV17HW741R8EMdaJ9l8ld+kWvvNArC9WGg054gTAkxf1Qz+P+9IKCE/fAjhz7AZa408dkmmnfQwr71WmmAaKHslWqru5AUOfcPa3tt+uQc7Jqn3A44m1AKvqs3yEkcGmfYy25gtKGnridCJ9sfF84sw7c4me8Nxbx+IUUtA+93txJZhWfLuxHt2Q0VUAW6T0q1MXPcaMefvz9TtmuPk5sT63brXAUlOiggjlUxyGMZtAOqAhfZYvXd713MKjkRK4iqz1Y+gMeJNN3p/TKLUwWyh/mfZVZz0yLoFOXB5aCpBM+x4+qvVKjQIGlfJHVj6mtkJoJc="
        - secure: "IYw7MGxZ06gDDxzk+LeVPUWms2XFEttQf67Wbph7VtmGJWMUzmTZxOyfncrUA1W6fJHAD1DTj4UQkSjcwGeVASCXCpGF4WaElozXS+dW1JcKpMVvDfasDiwoK+MCsPbqF0HuHhbhWqyS3/v+Pst/Qi9xOIgAcDRe6NWv8FYOEuqfvPcszWD43U2f9b7yCruUcz2DOG460u7t/PQd81jtHNeC3c/+UsPtZ1wDwS1zGJCTs2PJ3oYGH1b3lGqHoEojTIqJMLqgfCs5wv1LfAFop+zMfDwWx01bRRcF2lSopHBFkx/eart93GIeIG7ZvDAuglc7dfGoGiF7vHoabfZsVBvjCdTdNZljABUSHvAKZUvbcaTkQUJe2nI+gpXjFyCU2NafdmJWVbjGDVL9kQmr6XOexEPtGyI740MDPHiwsicKNg3zDAZb0xA3hCnL82wJiCvRWxGQHpUF3FLFJ6GwcJPAkLrwt+KWfMrVeUow2Lgi21WDmv8suNiNHZ9S7IdbMzgFa7k4+Fok4G5tM6Pfcuf9eBIDwO3DLmXTn7rPBEMtJk77SvJRhlV9WgLiU7NSgalUhu4TM5pF73kiTpUyEYb2wmIlejiP9Jwqe2guSRNEvfpq+01Xxhtxaot50RQ82v27cMKLmt03p2MwCQyryHJskl+LO6d0+3PpRbibOac="
      install:
        - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64-2.0.30.zip" -o "awscliv2.zip"
        - unzip awscliv2.zip
        - sudo ./aws/install
      script:
        - cat cloudformation/cloudformation_deployer_role.yml
        - aws cloudformation validate-template --template-body file://cloudformation/cloudformation_deployer_role.yml
        - aws cloudformation deploy --template-file cloudformation/cloudformation_deployer_role.yml --stack-name CloudFormationDeployerRole --capabilities CAPABILITY_IAM
    - stage: Deploy Kubernetes IAM infrastructure
      env:
        - secure: "ndWCwNkaZ2Ro3CZtJPazU7MlYfqqWL7W6UYtyjtVQ9yhcJYTMtF+AyDAdxsEhYOmWszVeNp6A51ZGC3Xv020yGnGjnhemqGIYa0k5AA2iW7XEab/e9wTXJP720/kzZJZ4r32F0lTKQSUJVSgNmIitb4FcVgag9rpbUP5CRzSl7Ap5ksPo9crX1eTApbYR6OOKeVdDiAFGBqwwWEhrXf2OwJAtkkXSE50TFQ7UGjb8SaR8Cr2qhgKvUr9Fode3hfcQdAU4hotWFhVVqMVQLru5kWiAQJLAWyDm2EXWSO8PTm87S7GCiJMaHluddXR2zDMB7MlTgHYJhuo0J8e+99YN2n9Xq9+jALAT5uHvSIBbgH/KI4m7Tl6mX7ecsKOXLtRNlm5I18jdEXJfnL4ayWBRuPGqyThGyiJeCSewd37ohwY2hRQ/Iztqf4nlG3+C7VIz31NfTj/vO/s5J6TzPAIrrtCGfwnFyGYdYHYoJmhBl7JD9txyCV8iQ23Y3MEWwzkfByOhoKqI29SljSsiJmQbaM/bTQ60vWarcZ+iDiYm8VKbpDYjxUZDA9dZJJ7V0/26P1x4gxL8N2vPwYInPfmkml0Y2vjI0edTZ27PLmEhBbn5/3Hot3RcF/8nc3VlfmpcC8silicyzYXmZ7HosmvZicx6cYO/Y7y5BPh+2KDGoQ="
        - secure: "i6GhWPG5Ob3wz26ztG0NfqSHrAEAmICzNeQKucpfRLzcABc+n7Wh2m76gDV0luk8YYWL+YL4Dgv78F//laip3RR+nk0t966hgDf2M7HL4aUmef0jumZ5iT396hcp6NDjzcUkMB7H0ZZMykdaWwr9ZlO4cHPgUKtqOBcx0v8vN/cFj8t1qELZ3sVqCT4cJYmiNUZHeD60j3YuergXeHWOZDDPIdTTs19eGIHJRqZ3+qaUHvWp0HdJTt2Z1Kty587QbsEfF9tLRH4zTsknx3nBD0vlybDlA8ZNCSGHeLR5W84EpYXQpCOemOaN3ecD81F50YFJir7WQEP8ZmdoO+2kdmlfeEcgeRAL4dsGpvriD70M1Ni3KEKTUzC/lWIs3NhXeD30ojqp8TAwILAI4JUYPHXTRlqSxQMztVDga/9Jeik5NL8xnCQCpZ+JLWWVzvEgTATq9Qrms8rMRjtyt4/e1JJq1oJm88pThck0BA7UqV6rR20aqYocMVfblcSEtdi9ppWdJWj289vyj2WJ99xWuDUyoNnPdVAnIMqmz8SydZrzfKpzDQPCf7XHdrePufqbrgrlWFzFjEiINLCJbQ3dzHRysiEDgi3nXxP7vjL07B6mEAD43BqNx0VdEdiRjrWNfnc7U/FyjoCgJ0PdeoZp8WNV2yy1QdhWOO8/fKCKzdo="
        - secure: "BpiKWFmOY8E3MsjopfW7Sy6uafdKLpbpEVarykdhItNqIJ9nrFjvnxvGMvEqTR4fwo/PulIo2kGlHr+kh7mogjIJ+yZEnFHfwePsrxSgCII0LYR2F/ROOR9KalnCc4rIUMfdNs+iiafbve+EebDq0m9b0wXQgUrt2Ud/O66G86Gu9csocGwk1+V2D2DsTKxagCtvfleBVpFML10s+H1KUzUr2RAHJSV2gCJKBkN1tEdntMeVXUD08CDg4JQ3d/8G7ZF6dS2et2c1eJQyH40PUwBgQtvDAjmvtGYBV7T+xlqRgMY2AcrqPhwiFqplUEHTH03w8CgTFPOZCJtS9rLSXV9FMkG3HkVLPsS2MPko4tmqVlB9j0MUfPUvUNRMKjSiIk4p2S4TcdK1govJWJ4dEHaFL/cMhSLZiYVaZ4av47ax5gyvDyP4kxdlQM9hyev0oaOYSQULYEzZxr9lOM30DLLCl9RZJ9uRay6jUg5hyXMP6AamRHz5Fbinui1Ae3D7C66ngV/Z3ZNfW62JbunFLt6qvokEHyK1AySLA8SdM4SO1OhO01J+xqPXXTqn7wU2Mie7h9Ao23QtbAUixaobJWyjS7ncaDqlAKGUB0G2jJ6mU+zaiBUuUJWi8q1o1dDZX1DFsdNtZcSm9hF91WnCxoTfmaQjA8o9L8BnuYybxdk="
      install:
        - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64-2.0.30.zip" -o "awscliv2.zip"
        - unzip awscliv2.zip
        - sudo ./aws/install
      script:
        - STS_CREDENTIALS=$(aws sts assume-role --role-arn $AWS_ROLE_ARN --role-session-name CloudFormationDeploymentSession | jq -r '.Credentials')
        - AWS_ACCESS_KEY_ID_STS=$(echo $STS_CREDENTIALS | jq -r '.AccessKeyId')
        - AWS_SECRET_ACCESS_KEY_STS=$(echo $STS_CREDENTIALS | jq -r '.SecretAccessKey')
        - AWS_SESSION_TOKEN_STS=$(echo $STS_CREDENTIALS | jq -r '.SessionToken')
        - AWS_ACCESS_KEY_ID=$(echo $AWS_ACCESS_KEY_ID_STS)
        - AWS_SECRET_ACCESS_KEY=$(echo $AWS_SECRET_ACCESS_KEY_STS)
        - AWS_SESSION_TOKEN=$(echo $AWS_SESSION_TOKEN_STS)
        - cat cloudformation/iam.yml
        - aws cloudformation validate-template --template-body file://cloudformation/iam.yml
        - aws cloudformation deploy --template-file cloudformation/iam.yml --stack-name CloudFormationDeployerRole --capabilities CAPABILITY_IAM
