language: generic
env:
  global:
  - AWS_DEFAULT_REGION=us-east-1
  - secure: S+OXmX1ac2SokftIVRs7M2OLR5n3H1ZKlTYut0yvZWrdG8Iws4delsu1EumYjY/PveeYQHKx2+TJsfuOWnNs3axj0x4nOcsfYqtYTKctKRIIFB7ardkcPRqrsEz5ZrokMu4bLFyeGjvRZrQPn0OfMrJS4hgJhe96cpmgz/53YfSYUqfpkGmrNmXcHYQxR1CUsMOf9u5ACP6MNVhn6nGpqDyzvtEyNhLMylRyvMShN1FFOwR073QAeYjOt6mNaqDCAjPb1gRZY4g3xEEIJbSyglbKUMNLdUEZBvRk//2DL7ohMvN3eFQPQkBT2Ym6ED3zKs60DAORPaq9648/hLQLUVnEwsRBJSYSgVQMeiTP5QcoePDa6yX70MSD3rWZmOUAAWPTpcvLW6WV+P7QdKHaPHlo1f6daHSKB4iB+0OoQTp/7m6MxlOAzxPhjSMcb7QlE/T2km+3iR2lS9qvKirGRY7MyjEx2TQeJAtvH9LcNlc394U8g2+lQJ2xbkmD4Y6kLcadHi4f8ZPtZGszrX1jnaZ8m1ddRlKLzVQpi6wdMTxpwJEhfJRUTjWhnAaA3zLCTYx2XqeYINSRAlFVBNq5+87ciHOzh+Oolhrs8WTTJWAMMaTPgq4gh5WId3ccXCn5angctS3hkFDrPDvRdT+dSYFW21CgAu6SUFLUuZlHPgc=
  - secure: Y+Z1TZ0H0MYfy2oi9U4qV7XzNWrOuw9cZnLwfKlfEXQiqT6kHlKWt49lhluekWa1jVUFVN4C9Rtcfpd66hTjHd8t8FnlpOs1bjG9rD2/lBEmF7spngBShiSFpmlO5ICkeAQlXlnTzqUVvGZ6VUyPj2jgQ1ajLVrQ1ArSCwssaqi+myJ6BTkSIzMDDEieBR00QYPtN9Hm6FD7/uFdtQ+7JeeEdhA3miVUrT7O8M7Xgzdwqflcc+hlgYlr8onG9Xkh/uaqnGl2bo5p9+lDLMIzaJzeu5vBzlvf6tisQ2Bg7wlV1nZcUjm6CB0bgiVZPpJCoe1QQIpGsMc/H4jnYwfYs0/GN6i7KDJRCLyomNVOijrhWPSgzKjBubjp/4Kx6RJZzHqtLMlEK79/5475hzAE/X12rfCirxLh8j3JZqGcGrEcDoWSkgnOnfbNVoHRh/Nt/dTfAF4JEn41tAJrChcVTLrRRQZVaMN0miZlUuURMVO6b8T/m9Hp8ozsz3GnPKFotsa+rNaM0hEo6SIP92+F36BUHsxErBlozVZMu5hVSmsQucBfgvi6SML3sS4SMjO85lZrKyJhvDi8BqqDWUk9bUdzgZzKrglF2gDHfGgZucc74Eb4kVwThpu9Fv/z9kaOJZJJO5G1EVpNoVz9xx0a+BOtCh+8B3dKcf7bvqVjEQ4=
before_install:
- echo "Installing AWS CLI"
- pip install --upgrade --user awscli
install: true
script:
- aws cloudformation validate-template --template-body file://cloudformation/my-template.yml
after_success:
- echo "Test Success - Branch($TRAVIS_BRANCH) Pull Request($TRAVIS_PULL_REQUEST) Tag($TRAVIS_TAG)"
- echo "Cloudformation template validated"
- echo "YAML linted"
