language: generic
os: linux
arch:
  - amd64
branches:
  - main
env:
  global:
  - AWS_DEFAULT_REGION=us-east-1

jobs:
  include:
    - stage: Create bootstrap resources
      env:
        - secure: "NTDkW1owt0tIXbd2BoLjcUHunQYlsD+NMW3zVASAw40KI2EavoI4ZhGg9UOe+0Aym/LaWMA7E0HNfMBNiLHochBEoxcL8rWRvCLeS1O0nNuTSx/wG/2L5AMoTkZhQ3ibfovJAN/mgkrtRk8hC/xHi5H/GxZzwEQlCT7vK2MH/xNJfStwLvcHnyYZlPcAML9b1xogETsoJyPPc9Sw1nVnJrUuT1plk3Jw/CTTYyD4JFt6tuNXBrkKpI4viAO7Kf2rdD6JQAUKw4IgRDzcoLQFIF0SSn3xQ/PQZrHF/u0e3gU+FBK/7L9vEa0IukopLJvqng12JGZtmUos1OUuKXnRcEyllshWmYz3SPPfXcV17HW741R8EMdaJ9l8ld+kWvvNArC9WGg054gTAkxf1Qz+P+9IKCE/fAjhz7AZa408dkmmnfQwr71WmmAaKHslWqru5AUOfcPa3tt+uQc7Jqn3A44m1AKvqs3yEkcGmfYy25gtKGnridCJ9sfF84sw7c4me8Nxbx+IUUtA+93txJZhWfLuxHt2Q0VUAW6T0q1MXPcaMefvz9TtmuPk5sT63brXAUlOiggjlUxyGMZtAOqAhfZYvXd713MKjkRK4iqz1Y+gMeJNN3p/TKLUwWyh/mfZVZz0yLoFOXB5aCpBM+x4+qvVKjQIGlfJHVj6mtkJoJc="
        - secure: "IYw7MGxZ06gDDxzk+LeVPUWms2XFEttQf67Wbph7VtmGJWMUzmTZxOyfncrUA1W6fJHAD1DTj4UQkSjcwGeVASCXCpGF4WaElozXS+dW1JcKpMVvDfasDiwoK+MCsPbqF0HuHhbhWqyS3/v+Pst/Qi9xOIgAcDRe6NWv8FYOEuqfvPcszWD43U2f9b7yCruUcz2DOG460u7t/PQd81jtHNeC3c/+UsPtZ1wDwS1zGJCTs2PJ3oYGH1b3lGqHoEojTIqJMLqgfCs5wv1LfAFop+zMfDwWx01bRRcF2lSopHBFkx/eart93GIeIG7ZvDAuglc7dfGoGiF7vHoabfZsVBvjCdTdNZljABUSHvAKZUvbcaTkQUJe2nI+gpXjFyCU2NafdmJWVbjGDVL9kQmr6XOexEPtGyI740MDPHiwsicKNg3zDAZb0xA3hCnL82wJiCvRWxGQHpUF3FLFJ6GwcJPAkLrwt+KWfMrVeUow2Lgi21WDmv8suNiNHZ9S7IdbMzgFa7k4+Fok4G5tM6Pfcuf9eBIDwO3DLmXTn7rPBEMtJk77SvJRhlV9WgLiU7NSgalUhu4TM5pF73kiTpUyEYb2wmIlejiP9Jwqe2guSRNEvfpq+01Xxhtxaot50RQ82v27cMKLmt03p2MwCQyryHJskl+LO6d0+3PpRbibOac="
      install:
        - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        - unzip awscliv2.zip
        - sudo ./aws/install
        - aws --version
      script:
        - cat cloudformation/bootstrap_resources.yml
        - aws cloudformation validate-template --template-body file://cloudformation/bootstrap_resources.yml
        - aws cloudformation deploy --template-file cloudformation/bootstrap_resources.yml --stack-name BootstrapResources --capabilities CAPABILITY_IAM
        - aws cloudformation list-exports | jq -r '.Exports[] | select(.Name=="BootstrapResources-RoleArn") | .Value' > rolearn
        - aws cloudformation list-exports | jq -r '.Exports[] | select(.Name=="BootstrapResources-CloudFormationTemplatesBucketName") | .Value' > cfbucketname
        - date -u +"%Y/%m/%d/%H/%M/%S" > cfkeyprefix
        - cat cfkeyprefix
      workspaces:
        create:
          name: ws1
          paths:
            - rolearn
            - cfbucketname
            - cfkeyprefix
    - stage: Validate CloudFormation templates and upload them to S3
      workspaces:
        use: ws1
      env:
        - secure: "qFl6jyD5osATGVZMbjOM5rn5sGVp0/yzaJQONVAuT+urmOUM4c/Vz01rkQnuRdtjdwe/ya7F0TrJNidu5yQOKF41acQYE5ZcM5yq/yceKcmyDkVJ2Kjtu8dsoAMX7pjrj4/bF9hKPQEjiB519KK7OnitQg15EsRK4nSVq1J6oyqNSNmm/nysQYGGwF9iKpQ4KbbW+woixq4w287hfwvipAdLsVt7oWEU4bV4URk7IKFzyYOpTyR2zqEIPMNjTnbdmqWG+8Prs+fa1da6SzBwUtxsV0b8c/DjtmfYDtXeWCgfIkyNXorLsxpI0/z6XJhxt0YR/lp711glrSeH21VRX8f/BTMqBzSpq01yNGxjNhyzAJ789y7T/MEcJ28YJ+dtycL8G+7TotFLTdbWdZMy1YGMezk78mTvGrqZWBhKyDfvD1mG+TZ6PQK07TJoLB6sa1KXemTb3/chuMVQ/KsKE2n0xNxPY9Iip27cGJNJdJnvWKKOFoCUlk8bQE4KKegL5uDGn9ZLwR8/2rnY8QKDU+OvGSvOYw0A+cV+rKmTrfyoIdiFUEVB9aq4vGEVsCU4CNJxPdgDIh/yawvVlCajoibHvpwI/jvxVrmMguoekcz1S2Hsi4bTJTX58Fe4OaQjl3HJRGy3x6dZ7jiPFoLeGnaEdvCagfawq9V8JWGm4C0="
        - secure: "Nnd1mUgCmQ33+Ja7MZvc8TXLRnotdDEOSMW2kx4tIEzNwnqdjI/7F7EFxgZnTBrCGSPdBT52QzFWxuKchVVhgxxGntiXleGBq+yz1qBbLgkMDtkLBFLqC13shoLc/qZNQlLyb1aTVP0d2zDlvxn2xplL1oafC63NsRIx/2e9WVfY1bPx5hxoGaC+IX+JWPeVi56Q+hW3D9oPPokftYCKWfZSKPkPcUZyjvdOBDk/WfftHYfUNQwZViOgivvH85DvXQxqX+GvV1aZrfZRawUo8dbi3GV2p1VZubs4s5UeXyqRRBzmD0DN3fgdkN9e5zfzFyDvqNCSG3zm0JAUjAlCL/joFHdiBMKqQVpif4GURFVWOVb1hihhq42sK65ITRb72akhEzF0CH0rrz5qqLFHW+JfQ7p7l5UNJ9LWgYP9TQdQ9djsTFxTekfkjdLMl0hAq8MUtNRY6t8i+bXPHoG7K9k2j899AQXQ2D45vUc2ggQVOUsRdUAJHW/1YTxLVzPc4Pou28+O9w02ptDMA0QGgZ/+gWQy4wcinCo7Ea/xvdSSkIK/nmncGZHOziUUxUArRuWfzEJuXAOhOgxu5g2etbfGhg4OnZlbi3qfBBqQd+DFNrz9qFTvvYjJg7xqt0vRLJxyD/N1Efs2XjaiGCMPWiWmtxSNDhJjynVNYY4AxPE="
      install:
        - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        - unzip awscliv2.zip
        - sudo ./aws/install
        - aws --version
      script:
        - export AWS_ROLE_ARN=$(cat rolearn)
        - export STS_CREDENTIALS=$(aws sts assume-role --role-arn $AWS_ROLE_ARN --role-session-name ValidateAndS3UploadTemplatesSession | jq -r '.Credentials') >/dev/null 2>&1
        - export AWS_ACCESS_KEY_ID_STS=$(echo $STS_CREDENTIALS | jq -r '.AccessKeyId') >/dev/null 2>&1
        - export AWS_SECRET_ACCESS_KEY_STS=$(echo $STS_CREDENTIALS | jq -r '.SecretAccessKey') >/dev/null 2>&1
        - export AWS_SESSION_TOKEN_STS=$(echo $STS_CREDENTIALS | jq -r '.SessionToken') >/dev/null 2>&1
        - export AWS_ACCESS_KEY_ID=$(echo $AWS_ACCESS_KEY_ID_STS) >/dev/null 2>&1
        - export AWS_SECRET_ACCESS_KEY=$(echo $AWS_SECRET_ACCESS_KEY_STS) >/dev/null 2>&1
        - export AWS_SESSION_TOKEN=$(echo $AWS_SESSION_TOKEN_STS) >/dev/null 2>&1
        - export CF_BUCKET=s3://$(cat cfbucketname)
        - export CF_KEY_PREFIX=$(cat cfkeyprefix)
        - cat cloudformation/cloudformation_template.yml
        - aws cloudformation validate-template --template-body file://cloudformation/cloudformation_template.yml
        - cat cloudformation/vpc.yml
        - aws cloudformation validate-template --template-body file://cloudformation/vpc.yml
        - aws s3 cp cloudformation/vpc.yml $CF_BUCKET/$CF_KEY_PREFIX/
        - cat cloudformation/kubernetes_infrastructure.yml
        - aws cloudformation validate-template --template-body file://cloudformation/kubernetes_infrastructure.yml
        - aws s3 cp cloudformation/kubernetes_infrastructure.yml $CF_BUCKET/$CF_KEY_PREFIX/
    - stage: Deploy CloudFormation infrastructure
      workspaces:
        use: ws1
      env:
        - secure: "qFl6jyD5osATGVZMbjOM5rn5sGVp0/yzaJQONVAuT+urmOUM4c/Vz01rkQnuRdtjdwe/ya7F0TrJNidu5yQOKF41acQYE5ZcM5yq/yceKcmyDkVJ2Kjtu8dsoAMX7pjrj4/bF9hKPQEjiB519KK7OnitQg15EsRK4nSVq1J6oyqNSNmm/nysQYGGwF9iKpQ4KbbW+woixq4w287hfwvipAdLsVt7oWEU4bV4URk7IKFzyYOpTyR2zqEIPMNjTnbdmqWG+8Prs+fa1da6SzBwUtxsV0b8c/DjtmfYDtXeWCgfIkyNXorLsxpI0/z6XJhxt0YR/lp711glrSeH21VRX8f/BTMqBzSpq01yNGxjNhyzAJ789y7T/MEcJ28YJ+dtycL8G+7TotFLTdbWdZMy1YGMezk78mTvGrqZWBhKyDfvD1mG+TZ6PQK07TJoLB6sa1KXemTb3/chuMVQ/KsKE2n0xNxPY9Iip27cGJNJdJnvWKKOFoCUlk8bQE4KKegL5uDGn9ZLwR8/2rnY8QKDU+OvGSvOYw0A+cV+rKmTrfyoIdiFUEVB9aq4vGEVsCU4CNJxPdgDIh/yawvVlCajoibHvpwI/jvxVrmMguoekcz1S2Hsi4bTJTX58Fe4OaQjl3HJRGy3x6dZ7jiPFoLeGnaEdvCagfawq9V8JWGm4C0="
        - secure: "Nnd1mUgCmQ33+Ja7MZvc8TXLRnotdDEOSMW2kx4tIEzNwnqdjI/7F7EFxgZnTBrCGSPdBT52QzFWxuKchVVhgxxGntiXleGBq+yz1qBbLgkMDtkLBFLqC13shoLc/qZNQlLyb1aTVP0d2zDlvxn2xplL1oafC63NsRIx/2e9WVfY1bPx5hxoGaC+IX+JWPeVi56Q+hW3D9oPPokftYCKWfZSKPkPcUZyjvdOBDk/WfftHYfUNQwZViOgivvH85DvXQxqX+GvV1aZrfZRawUo8dbi3GV2p1VZubs4s5UeXyqRRBzmD0DN3fgdkN9e5zfzFyDvqNCSG3zm0JAUjAlCL/joFHdiBMKqQVpif4GURFVWOVb1hihhq42sK65ITRb72akhEzF0CH0rrz5qqLFHW+JfQ7p7l5UNJ9LWgYP9TQdQ9djsTFxTekfkjdLMl0hAq8MUtNRY6t8i+bXPHoG7K9k2j899AQXQ2D45vUc2ggQVOUsRdUAJHW/1YTxLVzPc4Pou28+O9w02ptDMA0QGgZ/+gWQy4wcinCo7Ea/xvdSSkIK/nmncGZHOziUUxUArRuWfzEJuXAOhOgxu5g2etbfGhg4OnZlbi3qfBBqQd+DFNrz9qFTvvYjJg7xqt0vRLJxyD/N1Efs2XjaiGCMPWiWmtxSNDhJjynVNYY4AxPE="
      install:
        - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        - unzip awscliv2.zip
        - sudo ./aws/install
        - aws --version
      script:
        - export AWS_ROLE_ARN=$(cat rolearn)
        - export STS_CREDENTIALS=$(aws sts assume-role --role-arn $AWS_ROLE_ARN --role-session-name KubernetesStackSession  | jq -r '.Credentials') >/dev/null 2>&1
        - export AWS_ACCESS_KEY_ID_STS=$(echo $STS_CREDENTIALS | jq -r '.AccessKeyId') >/dev/null 2>&1
        - export AWS_SECRET_ACCESS_KEY_STS=$(echo $STS_CREDENTIALS | jq -r '.SecretAccessKey') >/dev/null 2>&1
        - export AWS_SESSION_TOKEN_STS=$(echo $STS_CREDENTIALS | jq -r '.SessionToken') >/dev/null 2>&1
        - export AWS_ACCESS_KEY_ID=$(echo $AWS_ACCESS_KEY_ID_STS) >/dev/null 2>&1
        - export AWS_SECRET_ACCESS_KEY=$(echo $AWS_SECRET_ACCESS_KEY_STS) >/dev/null 2>&1
        - export AWS_SESSION_TOKEN=$(echo $AWS_SESSION_TOKEN_STS) >/dev/null 2>&1
        - export CF_URL=https://$(cat cfbucketname).s3.amazonaws.com
        - export CF_KEY_PREFIX=$(cat cfkeyprefix)
        - travis_wait 30 aws cloudformation deploy --template-file cloudformation/cloudformation_template.yml --stack-name KubernetesStack --capabilities CAPABILITY_IAM --parameter-overrides CloudFormationTemplatesBucketName=$CF_URL VPCInfrastructureKey=$CF_KEY_PREFIX/vpc.yml KubernetesInfrastructureKey=$CF_KEY_PREFIX/kubernetes_infrastructure.yml