language: generic
env:
  global:
  - AWS_DEFAULT_REGION=us-east-1

jobs:
  include:
    - stage: Deploy CloudFormation role
      script: skip
      deploy:
        - provider: cloudformation
          access_key_id:
            secure: "ajJfUkTNeeLfxXaoXigobZV4LM+v1qXr5i1w8edAMnL1AvRdscKyPLKAhiSHf6DBXDxXdnTLCDsO7DiDvqIc3lKlmj3zwbwQ1TwAdkEe0xTBqU3Uql7ohbOBuEUup1Dp/HNDYA/vIhyIlaenK51eOz4qfFN2CWrCHFY6K5Tt0dhu9K6ORcF5XnsWNKSSVJuo7Lt6vjcMJUtQTgd5n0IkraGmW5cg4dZVwpSor14RThREW0b3lWyZOjtxAnrQJxiLcvfO/mPMpjgJNttG0/UJiH+KRJji0oJfZrNMQSIicTNYuMuGxmN7YXFPz2FaoXiOKUOyDpXOE6PvcSN5W2klBEEcYstQA4t+JLnxQs+ReBbi9dPALamkgPB7BGiM0EO+Ss55Fn8hY+mACOYC+D4UqB7M7FHZBrnBw80qDBtvDcbpSx82cHdf2WytzSiyn2W/uzApChVUi/Djydg30T1n3M2/JKnZQ7kmzy+In3KQIm5ErVF1imOvoowDa6A8XdlxjQUSoGCCSnrU5gkuoIk3dX6GhLNRn5tNKQO+LJ25xRhDgHi9syyVhq5g4Rvmd2YJ0h1QEGi7tYclgkvvWXnEVUQyKr3/hiU0I7Zbno4pYiiCC1yVdjAlm/kBHAhe3V2aM7x8noJ4NeBwVh2X0CLu+8Sr73/z3+1/yAiEM7DhtKA="
          secret_access_key:
            secure: "LL8f0Ak8LCr+Pes++oRFxur/kDa+q7V+/73ZkwSpt9L+mNCCdC5GOGkCECeUp30viDhmFnzaeHo4UUxeU+PNC8fvqCMVbzvpk7nS55uoSVxPOYY3OXUd1+H726Gi043/5JcLwCIVYkyQ1BsRuuQmz/i1oblHwaXUl15uUxgv7UIOc2313d4KgnpgwlQcybZ/1FiBKoXHoS91nKi5l56ySX4PGYcUk6LKIqTEZe2PS6d9OkmsHpSfryTr2Rpz6RslfOiTL4k0OnLs6fOSrE0MD/Ei1u5T4CQ9AuV95h+XxSSsfmeByDaiLYPTEjacuDP6su/K4CNRwCq7CPbF7xiU1ZmBakAyjKC0YmlzJX1cHpKaA8dJiWo0ifg7gkYT1uioHGBVs/nlPlEpw1G/P8HRj5ITcfIWfOi1xMVWdFh8v/dXDqLDThY4Kv5oOLaRj9PAyVvqAo97vjjXJJbix+oTv7Hw8184DsDgBZ0BUt2eZOqA0wv0sw/xl/n+9ZJN3m9igL94VzBcF97FkySSdCuYgWsyYXnYib39H8RQ9edBZneTHECgZwQd/csklATGj/TbZIXgo4InQbB2c9sElv34oLJ9aSLgfTxTIqqYfacsVg1M/mkYE6TeqWU2JU8joe/7naNT7UeacIhqO7+kNKcayInCGv4T8dPVCpqppmj9sIY="
          template: cloudformation/cloudformation.yml
          stack_name: KubernetesInfrastructure
          capabilities: CAPABILITY_IAM
          edge: true
          on:
            branch: main
    - stage: Deploy IAM users
      script: skip
      deploy:
        - provider: cloudformation
          access_key_id:
            secure: "ajJfUkTNeeLfxXaoXigobZV4LM+v1qXr5i1w8edAMnL1AvRdscKyPLKAhiSHf6DBXDxXdnTLCDsO7DiDvqIc3lKlmj3zwbwQ1TwAdkEe0xTBqU3Uql7ohbOBuEUup1Dp/HNDYA/vIhyIlaenK51eOz4qfFN2CWrCHFY6K5Tt0dhu9K6ORcF5XnsWNKSSVJuo7Lt6vjcMJUtQTgd5n0IkraGmW5cg4dZVwpSor14RThREW0b3lWyZOjtxAnrQJxiLcvfO/mPMpjgJNttG0/UJiH+KRJji0oJfZrNMQSIicTNYuMuGxmN7YXFPz2FaoXiOKUOyDpXOE6PvcSN5W2klBEEcYstQA4t+JLnxQs+ReBbi9dPALamkgPB7BGiM0EO+Ss55Fn8hY+mACOYC+D4UqB7M7FHZBrnBw80qDBtvDcbpSx82cHdf2WytzSiyn2W/uzApChVUi/Djydg30T1n3M2/JKnZQ7kmzy+In3KQIm5ErVF1imOvoowDa6A8XdlxjQUSoGCCSnrU5gkuoIk3dX6GhLNRn5tNKQO+LJ25xRhDgHi9syyVhq5g4Rvmd2YJ0h1QEGi7tYclgkvvWXnEVUQyKr3/hiU0I7Zbno4pYiiCC1yVdjAlm/kBHAhe3V2aM7x8noJ4NeBwVh2X0CLu+8Sr73/z3+1/yAiEM7DhtKA="
          secret_access_key:
            secure: "LL8f0Ak8LCr+Pes++oRFxur/kDa+q7V+/73ZkwSpt9L+mNCCdC5GOGkCECeUp30viDhmFnzaeHo4UUxeU+PNC8fvqCMVbzvpk7nS55uoSVxPOYY3OXUd1+H726Gi043/5JcLwCIVYkyQ1BsRuuQmz/i1oblHwaXUl15uUxgv7UIOc2313d4KgnpgwlQcybZ/1FiBKoXHoS91nKi5l56ySX4PGYcUk6LKIqTEZe2PS6d9OkmsHpSfryTr2Rpz6RslfOiTL4k0OnLs6fOSrE0MD/Ei1u5T4CQ9AuV95h+XxSSsfmeByDaiLYPTEjacuDP6su/K4CNRwCq7CPbF7xiU1ZmBakAyjKC0YmlzJX1cHpKaA8dJiWo0ifg7gkYT1uioHGBVs/nlPlEpw1G/P8HRj5ITcfIWfOi1xMVWdFh8v/dXDqLDThY4Kv5oOLaRj9PAyVvqAo97vjjXJJbix+oTv7Hw8184DsDgBZ0BUt2eZOqA0wv0sw/xl/n+9ZJN3m9igL94VzBcF97FkySSdCuYgWsyYXnYib39H8RQ9edBZneTHECgZwQd/csklATGj/TbZIXgo4InQbB2c9sElv34oLJ9aSLgfTxTIqqYfacsVg1M/mkYE6TeqWU2JU8joe/7naNT7UeacIhqO7+kNKcayInCGv4T8dPVCpqppmj9sIY="
          template: cloudformation/iam.yml
          stack_name: KubernetesInfrastructure
          capabilities: CAPABILITY_IAM
          edge: true
          on:
            branch: main
