language: generic
os: linux
arch:
  - amd64
branches:
  - main
env:
  global:
  - AWS_DEFAULT_REGION=us-east-1

jobs:
  include:
    - stage: Create bootstrap resources
      env:
        - secure: "NTDkW1owt0tIXbd2BoLjcUHunQYlsD+NMW3zVASAw40KI2EavoI4ZhGg9UOe+0Aym/LaWMA7E0HNfMBNiLHochBEoxcL8rWRvCLeS1O0nNuTSx/wG/2L5AMoTkZhQ3ibfovJAN/mgkrtRk8hC/xHi5H/GxZzwEQlCT7vK2MH/xNJfStwLvcHnyYZlPcAML9b1xogETsoJyPPc9Sw1nVnJrUuT1plk3Jw/CTTYyD4JFt6tuNXBrkKpI4viAO7Kf2rdD6JQAUKw4IgRDzcoLQFIF0SSn3xQ/PQZrHF/u0e3gU+FBK/7L9vEa0IukopLJvqng12JGZtmUos1OUuKXnRcEyllshWmYz3SPPfXcV17HW741R8EMdaJ9l8ld+kWvvNArC9WGg054gTAkxf1Qz+P+9IKCE/fAjhz7AZa408dkmmnfQwr71WmmAaKHslWqru5AUOfcPa3tt+uQc7Jqn3A44m1AKvqs3yEkcGmfYy25gtKGnridCJ9sfF84sw7c4me8Nxbx+IUUtA+93txJZhWfLuxHt2Q0VUAW6T0q1MXPcaMefvz9TtmuPk5sT63brXAUlOiggjlUxyGMZtAOqAhfZYvXd713MKjkRK4iqz1Y+gMeJNN3p/TKLUwWyh/mfZVZz0yLoFOXB5aCpBM+x4+qvVKjQIGlfJHVj6mtkJoJc="
        - secure: "IYw7MGxZ06gDDxzk+LeVPUWms2XFEttQf67Wbph7VtmGJWMUzmTZxOyfncrUA1W6fJHAD1DTj4UQkSjcwGeVASCXCpGF4WaElozXS+dW1JcKpMVvDfasDiwoK+MCsPbqF0HuHhbhWqyS3/v+Pst/Qi9xOIgAcDRe6NWv8FYOEuqfvPcszWD43U2f9b7yCruUcz2DOG460u7t/PQd81jtHNeC3c/+UsPtZ1wDwS1zGJCTs2PJ3oYGH1b3lGqHoEojTIqJMLqgfCs5wv1LfAFop+zMfDwWx01bRRcF2lSopHBFkx/eart93GIeIG7ZvDAuglc7dfGoGiF7vHoabfZsVBvjCdTdNZljABUSHvAKZUvbcaTkQUJe2nI+gpXjFyCU2NafdmJWVbjGDVL9kQmr6XOexEPtGyI740MDPHiwsicKNg3zDAZb0xA3hCnL82wJiCvRWxGQHpUF3FLFJ6GwcJPAkLrwt+KWfMrVeUow2Lgi21WDmv8suNiNHZ9S7IdbMzgFa7k4+Fok4G5tM6Pfcuf9eBIDwO3DLmXTn7rPBEMtJk77SvJRhlV9WgLiU7NSgalUhu4TM5pF73kiTpUyEYb2wmIlejiP9Jwqe2guSRNEvfpq+01Xxhtxaot50RQ82v27cMKLmt03p2MwCQyryHJskl+LO6d0+3PpRbibOac="
      install:
        - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        - unzip awscliv2.zip
        - sudo ./aws/install
        - aws --version
      script:
        - cat cloudformation/bootstrap_resources.yml
        - aws cloudformation validate-template --template-body file://cloudformation/bootstrap_resources.yml
        - aws cloudformation deploy --template-file cloudformation/bootstrap_resources.yml --stack-name BootstrapResources --capabilities CAPABILITY_IAM
        - aws cloudformation list-exports | jq -r '.Exports[] | select(.Name=="BootstrapResources-RoleArn") | .Value' > rolearn
        - aws cloudformation list-exports | jq -r '.Exports[] | select(.Name=="BootstrapResources-CloudFormationTemplatesBucketName") | .Value' > cfbucketname
        - date -u +"%Y/%m/%d/%H/%M/%S" > cfkeyprefix
        - cat cfkeyprefix
      workspaces:
        create:
          name: ws1
          paths:
            - rolearn
            - cfbucketname
            - cfkeyprefix
    - stage: Validate CloudFormation templates and upload them to S3
      workspaces:
        use: ws1
      env:
        - secure: "qjqBPc0BN5WXnHTa8t5IdfZ4Wf5P7shviMQx9I6MqaXJsIcihkv26gZnHTuwNBpEy+7Tz8s5iQ0l/y8vGaiF1xu1giAfBN2o+v1iTWGmiGTyaa8Haqimpnrm8PuYUhFKozT43ru2zkJaHTX7ro4hBGOCprwaTIghkylzwWfoA9UfMUKBJcnDDopNmSdiRZDnvAN7tfma2ShU0R4Vva5J5VCTo4Qiyv0ZYwlgHFnTjsAlSqzTFSOGTJdE1cArKhD05pOs6PST5osmjATGx3EoHwBSS4WJCz7L1RY50TEe61rbN02tQp42IHaoqoUdKs/vMrqi64wufV2VNpNK2FQmG2QeA0XS+RScQI4YeC5Sy5UC/Hxa/vntqES7ZIEhVD+WZcgfLWYS3aYDImd86KvgFhOb/asZ6s71MO7xc8hlivdsGWV36jGs2pKy2VFVbuKrRVFziRrGQb4trsdWjIWwg2ISQjUeT2AUTjFf+S3af893SdfX5GafWt27C1OHfiz8hsdVciQjUaqQOTs3hbg1xMQZPqdSPVBGGczgnZsDL3mj16mpR2T/AgFj78h7KfGKEhjEeLXRqqKd+odCBHoGkK0WEyDscRUV/lIAYQM/A1s18NTiK6zGAh5hWLq8BidYYkLVWA2epJGTnEHQyqVRz4LbLgF4MGwR0s/aMZxKafE="
        - secure: "No+62dBqKChlIxrN48rDI3fXo+i/qOlp+2CwWob13hv9GX5yx35EZNZpDKJHUmdjZflH7MHcwbih6neB0kirHn6hSRwxXUqHoa6w0qlxd0MIRzmNOg9zb0yfGoF5JsMXHWZJ/57LZGRddDtJrkts1/1XfRwIUccj5XvAOMb1zVzjU0elTBZToutzE0bh36OAZaqh9UZwLaFxrEytQeXS7X/0R/Ub1icr24KaPsMLfvBv8N7YinLuIjVcXkhG2Jt4mYgxDvEQZsYsDv7u3NLMs47jrxOfBX66YddN7/cbPPvdk7WarXrs6fhAcUyI+HvQgAOjucnmZRtw1vTkRZloUhG2WtyxH9xl1ryfvIvAEZDEA/kk6nhrvl1jfzGacA131/ZAKZjx1SR9CJ3JxG529ktl5pvfBHdZP8X2rfzIvJIpmliZGQnsaH88+ILnY65pMmZ81BrFPr+E6UYlgf9O2xoD5WEdEd1F2HFtWtng27Q5GzlMpb+uJKm5PK+ka3gSthqgN6bg8RZR7o/I1HbsVLBBlv/+FC4ZWnQ6Or1eEdJ4ZaI8hIoOqlbfhdSeb6YLzPEKDC5ydzKJI0M2ouzIZox2YVIXNY/HO4h/5lZlSQksYV8dkYzqc01hMr9uET+/EBblm76HTjHs6Oz6tcLGH/2pO/78RPtcfKbUeFeOrXo="
      install:
        - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        - unzip awscliv2.zip
        - sudo ./aws/install
        - aws --version
      script:
        - export AWS_ROLE_ARN=$(cat rolearn)
        - export STS_CREDENTIALS=$(aws sts assume-role --role-arn $AWS_ROLE_ARN --role-session-name ValidateAndS3UploadTemplatesSession | jq -r '.Credentials') >/dev/null 2>&1
        - export AWS_ACCESS_KEY_ID_STS=$(echo $STS_CREDENTIALS | jq -r '.AccessKeyId') >/dev/null 2>&1
        - export AWS_SECRET_ACCESS_KEY_STS=$(echo $STS_CREDENTIALS | jq -r '.SecretAccessKey') >/dev/null 2>&1
        - export AWS_SESSION_TOKEN_STS=$(echo $STS_CREDENTIALS | jq -r '.SessionToken') >/dev/null 2>&1
        - export AWS_ACCESS_KEY_ID=$(echo $AWS_ACCESS_KEY_ID_STS) >/dev/null 2>&1
        - export AWS_SECRET_ACCESS_KEY=$(echo $AWS_SECRET_ACCESS_KEY_STS) >/dev/null 2>&1
        - export AWS_SESSION_TOKEN=$(echo $AWS_SESSION_TOKEN_STS) >/dev/null 2>&1
        - export CF_BUCKET=s3://$(cat cfbucketname)
        - export CF_KEY_PREFIX=$(cat cfkeyprefix)
        - cat cloudformation/cloudformation_template.yml
        - aws cloudformation validate-template --template-body file://cloudformation/cloudformation_template.yml
        - cat cloudformation/vpc.yml
        - aws cloudformation validate-template --template-body file://cloudformation/vpc.yml
        - aws s3 cp cloudformation/vpc.yml $CF_BUCKET/$CF_KEY_PREFIX/
        - cat cloudformation/kubernetes_infrastructure.yml
        - aws cloudformation validate-template --template-body file://cloudformation/kubernetes_infrastructure.yml
        - aws s3 cp cloudformation/kubernetes_infrastructure.yml $CF_BUCKET/$CF_KEY_PREFIX/
    - stage: Deploy CloudFormation infrastructure
      workspaces:
        use: ws1
      env:
        - secure: "qjqBPc0BN5WXnHTa8t5IdfZ4Wf5P7shviMQx9I6MqaXJsIcihkv26gZnHTuwNBpEy+7Tz8s5iQ0l/y8vGaiF1xu1giAfBN2o+v1iTWGmiGTyaa8Haqimpnrm8PuYUhFKozT43ru2zkJaHTX7ro4hBGOCprwaTIghkylzwWfoA9UfMUKBJcnDDopNmSdiRZDnvAN7tfma2ShU0R4Vva5J5VCTo4Qiyv0ZYwlgHFnTjsAlSqzTFSOGTJdE1cArKhD05pOs6PST5osmjATGx3EoHwBSS4WJCz7L1RY50TEe61rbN02tQp42IHaoqoUdKs/vMrqi64wufV2VNpNK2FQmG2QeA0XS+RScQI4YeC5Sy5UC/Hxa/vntqES7ZIEhVD+WZcgfLWYS3aYDImd86KvgFhOb/asZ6s71MO7xc8hlivdsGWV36jGs2pKy2VFVbuKrRVFziRrGQb4trsdWjIWwg2ISQjUeT2AUTjFf+S3af893SdfX5GafWt27C1OHfiz8hsdVciQjUaqQOTs3hbg1xMQZPqdSPVBGGczgnZsDL3mj16mpR2T/AgFj78h7KfGKEhjEeLXRqqKd+odCBHoGkK0WEyDscRUV/lIAYQM/A1s18NTiK6zGAh5hWLq8BidYYkLVWA2epJGTnEHQyqVRz4LbLgF4MGwR0s/aMZxKafE="
        - secure: "No+62dBqKChlIxrN48rDI3fXo+i/qOlp+2CwWob13hv9GX5yx35EZNZpDKJHUmdjZflH7MHcwbih6neB0kirHn6hSRwxXUqHoa6w0qlxd0MIRzmNOg9zb0yfGoF5JsMXHWZJ/57LZGRddDtJrkts1/1XfRwIUccj5XvAOMb1zVzjU0elTBZToutzE0bh36OAZaqh9UZwLaFxrEytQeXS7X/0R/Ub1icr24KaPsMLfvBv8N7YinLuIjVcXkhG2Jt4mYgxDvEQZsYsDv7u3NLMs47jrxOfBX66YddN7/cbPPvdk7WarXrs6fhAcUyI+HvQgAOjucnmZRtw1vTkRZloUhG2WtyxH9xl1ryfvIvAEZDEA/kk6nhrvl1jfzGacA131/ZAKZjx1SR9CJ3JxG529ktl5pvfBHdZP8X2rfzIvJIpmliZGQnsaH88+ILnY65pMmZ81BrFPr+E6UYlgf9O2xoD5WEdEd1F2HFtWtng27Q5GzlMpb+uJKm5PK+ka3gSthqgN6bg8RZR7o/I1HbsVLBBlv/+FC4ZWnQ6Or1eEdJ4ZaI8hIoOqlbfhdSeb6YLzPEKDC5ydzKJI0M2ouzIZox2YVIXNY/HO4h/5lZlSQksYV8dkYzqc01hMr9uET+/EBblm76HTjHs6Oz6tcLGH/2pO/78RPtcfKbUeFeOrXo="
      install:
        - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        - unzip awscliv2.zip
        - sudo ./aws/install
        - aws --version
      script:
        - export AWS_ROLE_ARN=$(cat rolearn)
        - export STS_CREDENTIALS=$(aws sts assume-role --role-arn $AWS_ROLE_ARN --role-session-name KubernetesStackSession  | jq -r '.Credentials') >/dev/null 2>&1
        - export AWS_ACCESS_KEY_ID_STS=$(echo $STS_CREDENTIALS | jq -r '.AccessKeyId') >/dev/null 2>&1
        - export AWS_SECRET_ACCESS_KEY_STS=$(echo $STS_CREDENTIALS | jq -r '.SecretAccessKey') >/dev/null 2>&1
        - export AWS_SESSION_TOKEN_STS=$(echo $STS_CREDENTIALS | jq -r '.SessionToken') >/dev/null 2>&1
        - export AWS_ACCESS_KEY_ID=$(echo $AWS_ACCESS_KEY_ID_STS) >/dev/null 2>&1
        - export AWS_SECRET_ACCESS_KEY=$(echo $AWS_SECRET_ACCESS_KEY_STS) >/dev/null 2>&1
        - export AWS_SESSION_TOKEN=$(echo $AWS_SESSION_TOKEN_STS) >/dev/null 2>&1
        - export CF_URL=https://$(cat cfbucketname).s3.amazonaws.com
        - export CF_KEY_PREFIX=$(cat cfkeyprefix)
        - travis_wait 30 aws cloudformation deploy --template-file cloudformation/cloudformation_template.yml --stack-name KubernetesStack --capabilities CAPABILITY_IAM --parameter-overrides CloudFormationTemplatesBucketName=$CF_URL VPCInfrastructureKey=$CF_KEY_PREFIX/vpc.yml KubernetesInfrastructureKey=$CF_KEY_PREFIX/kubernetes_infrastructure.yml