language: generic
os: linux
arch:
  - amd64
branches:
  - main
env:
  global:
  - AWS_DEFAULT_REGION=us-east-1

jobs:
  include:
    - stage: Deploy CloudFormation role
      env:
        - secure: "NTDkW1owt0tIXbd2BoLjcUHunQYlsD+NMW3zVASAw40KI2EavoI4ZhGg9UOe+0Aym/LaWMA7E0HNfMBNiLHochBEoxcL8rWRvCLeS1O0nNuTSx/wG/2L5AMoTkZhQ3ibfovJAN/mgkrtRk8hC/xHi5H/GxZzwEQlCT7vK2MH/xNJfStwLvcHnyYZlPcAML9b1xogETsoJyPPc9Sw1nVnJrUuT1plk3Jw/CTTYyD4JFt6tuNXBrkKpI4viAO7Kf2rdD6JQAUKw4IgRDzcoLQFIF0SSn3xQ/PQZrHF/u0e3gU+FBK/7L9vEa0IukopLJvqng12JGZtmUos1OUuKXnRcEyllshWmYz3SPPfXcV17HW741R8EMdaJ9l8ld+kWvvNArC9WGg054gTAkxf1Qz+P+9IKCE/fAjhz7AZa408dkmmnfQwr71WmmAaKHslWqru5AUOfcPa3tt+uQc7Jqn3A44m1AKvqs3yEkcGmfYy25gtKGnridCJ9sfF84sw7c4me8Nxbx+IUUtA+93txJZhWfLuxHt2Q0VUAW6T0q1MXPcaMefvz9TtmuPk5sT63brXAUlOiggjlUxyGMZtAOqAhfZYvXd713MKjkRK4iqz1Y+gMeJNN3p/TKLUwWyh/mfZVZz0yLoFOXB5aCpBM+x4+qvVKjQIGlfJHVj6mtkJoJc="
        - secure: "IYw7MGxZ06gDDxzk+LeVPUWms2XFEttQf67Wbph7VtmGJWMUzmTZxOyfncrUA1W6fJHAD1DTj4UQkSjcwGeVASCXCpGF4WaElozXS+dW1JcKpMVvDfasDiwoK+MCsPbqF0HuHhbhWqyS3/v+Pst/Qi9xOIgAcDRe6NWv8FYOEuqfvPcszWD43U2f9b7yCruUcz2DOG460u7t/PQd81jtHNeC3c/+UsPtZ1wDwS1zGJCTs2PJ3oYGH1b3lGqHoEojTIqJMLqgfCs5wv1LfAFop+zMfDwWx01bRRcF2lSopHBFkx/eart93GIeIG7ZvDAuglc7dfGoGiF7vHoabfZsVBvjCdTdNZljABUSHvAKZUvbcaTkQUJe2nI+gpXjFyCU2NafdmJWVbjGDVL9kQmr6XOexEPtGyI740MDPHiwsicKNg3zDAZb0xA3hCnL82wJiCvRWxGQHpUF3FLFJ6GwcJPAkLrwt+KWfMrVeUow2Lgi21WDmv8suNiNHZ9S7IdbMzgFa7k4+Fok4G5tM6Pfcuf9eBIDwO3DLmXTn7rPBEMtJk77SvJRhlV9WgLiU7NSgalUhu4TM5pF73kiTpUyEYb2wmIlejiP9Jwqe2guSRNEvfpq+01Xxhtxaot50RQ82v27cMKLmt03p2MwCQyryHJskl+LO6d0+3PpRbibOac="
      install:
        - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64-2.0.30.zip" -o "awscliv2.zip"
        - unzip awscliv2.zip
        - sudo ./aws/install
      script:
        - cat cloudformation/cloudformation_deployer_role.yml
        - aws cloudformation validate-template --template-body file://cloudformation/cloudformation_deployer_role.yml
        - aws cloudformation list-stacks
        - aws deploy --template-file cloudformation/cloudformation_deployer_role.yml --stack-name CloudFormationDeployerRole --capabilities CAPABILITY_IAM
    - stage: Deploy Kubernetes IAM infrastructure
      env:
        - secure: "QkG2SHEvzAq2IMn+obc4JPC9usOpm7YlhkSftXhi4IBer8aaQrpjm2G0KpTKcFfKuTxQFVtEigecI9cuBliAvOTm1wW8I/MdFHQ1xm61skEQWc+QV+PevPoQRRbkONE+Vhx5QwnXJUtEW8HP3W59wL6Xnu6OI3vN+NSNEBE3AxXTsua7zdPANt9U4e2UEL4jSziR//dYLTnLKLCOfwa6hhznEYq/vg/9wvKHaQFfvdTHIABC+5uvGq6sPenr+wS9ovalVFj+0JEnOgurwwD9LPHvGJvlrHa0XMaq98Y8ZRrCQl80YVDer+mqegl5V/yRx/N9p4LAwb4SrQ6IoGDUmSqTtJc4BkXICyR7zeLr/qj/wDEX+W5dn3/MxwXZmpyWWS8gW/qE2D9gztzz2eqExNEFHxkbXWlZHegMO/JHc4QEQthfQOp20P7X0H8E/K3DIa3ajSEcaCkpK1PT8v7IAppLtcYCtEXkDjsc6UJOUgEdFNZXUK+P35xnAUEFsyo9hC1RTRdp0/4P4VfJ0EKLXMpR8ctwu2nzEn5bRnWPc0g483x6fH3J3yeF7XqYjRzsTJeeHyi0EZaXm/9geRXZCcEPY+en63rjGMOoF4/rxlB41zv8LEBRKdZolpQyYNyOaN34F1anbndODkTaAdNPYkRniAEpAXMuEhRCOmMB3lY="
        - secure: "a8U3i32lu5kVdNJAJYaXlmCsQ6nzFMt0FD9z9Rn2rZQeFtE7zEy1Y49xaVrkZtMn5PmqLePHmUpNqx8I86vI7QUSiaO9Q61mCVkWjJcPrWsQyEEy0JAzAo7QI9SYTL55UJIZcdP2XkU3wEz+CIB4FaxXVaxkYO+PCfNuy05pFb7TWm2mI3nabTwSaoFF26N3hAU+/kEevrkgdZXtvQrw9XVaOantnboKYIszp6UU8tlkfPQLezwnQBUbpnfCzwYviKfGPXOfbTc41N+EpGKZl88070mYd2fHYGOxVs+YuEjWrGiu8x/Mu2qhKaDPj3b++v5iBzTPitxUcrYA8m3dk0DbD6B3aoI1kHAIOM9Zec5MZkvSQ4PyUoSd6MsSbtUJ66iQYmWkWzLigMBwRGY9gdP7EyuEkwpeJAzMeyiGgMhCUN+gHjhz1PXAt1TcgD6pRW3WvWaNEMoGBlsYotXpdQGLG+WU+15rLX4qPPsMjOtqjNFZz7IZzre7IixwwNFu3PyNA0Ddf3aE0nhXUSAPZnSU7VkMq4iTfb7aQE0vUYIKVc2U+CnvmjG8zB5LLSOUKngXEEkx5a8vnozSyMtERZPh+QVrr7DblcDdqNy7r6O/0Pg2Dhn+dcmJjNyUeNwVHAFARfCJwMRKMQ+XsG3ZzfRZ8Lzd91KIW5706UofjHs="
      install:
        - "/usr/bin/python -m pip install --upgrade pip"
        - pip install --upgrade --user awscli
      script:
        - cat cloudformation/iam.yml
        - aws cloudformation validate-template --template-body file://cloudformation/iam.yml
        - aws cloudformation list-stacks
